// {{PROJECT_NAME}} - SKSE Plugin with Papyrus Native Functions
// {{DESCRIPTION}}
// Author: {{AUTHOR}}
// Generated by Spooky's AutoMod Toolkit

#include "plugin.h"
#include "papyrus.h"

extern "C" DLLEXPORT bool SKSEAPI SKSEPlugin_Query(const SKSE::QueryInterface* a_skse, SKSE::PluginInfo* a_info)
{
    a_info->infoVersion = SKSE::PluginInfo::kVersion;
    a_info->name = PLUGIN_NAME;
    a_info->version = 1;

    if (a_skse->IsEditor()) {
        return false;
    }

    return true;
}

extern "C" DLLEXPORT constinit auto SKSEPlugin_Version = []() {
    SKSE::PluginVersionData v;
    v.PluginVersion(REL::Version{ {{VERSION_MAJOR}}, {{VERSION_MINOR}}, {{VERSION_PATCH}} });
    v.PluginName(PLUGIN_NAME);
    v.AuthorName(PLUGIN_AUTHOR);
    v.UsesAddressLibrary();
    v.UsesUpdatedStructs();
    v.CompatibleVersions({
        SKSE::RUNTIME_SSE_LATEST_AE,
        SKSE::RUNTIME_SSE_LATEST_SE
    });
    return v;
}();

extern "C" DLLEXPORT bool SKSEAPI SKSEPlugin_Load(const SKSE::LoadInterface* a_skse)
{
    SKSE::Init(a_skse);

    // Initialize logging
    auto path = SKSE::log::log_directory();
    if (path) {
        *path /= PLUGIN_NAME;
        *path += ".log";
        auto sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(path->string(), true);
        auto log = std::make_shared<spdlog::logger>("global log", std::move(sink));
        log->set_level(spdlog::level::info);
        log->flush_on(spdlog::level::info);
        spdlog::set_default_logger(std::move(log));
    }

    SKSE::log::info("{} v{} loaded", PLUGIN_NAME, PLUGIN_VERSION);

    // Register Papyrus functions
    auto papyrus = SKSE::GetPapyrusInterface();
    if (papyrus) {
        papyrus->Register({{PROJECT_NAME}}::Papyrus::RegisterFunctions);
        SKSE::log::info("Papyrus functions registered");
    }

    // Initialize plugin
    {{PROJECT_NAME}}::Plugin::Initialize();

    return true;
}
