#pragma once

// {{PROJECT_NAME}} - Papyrus Native Functions
// Generated by Spooky's AutoMod Toolkit
//
// Usage in Papyrus:
//   Import {{PROJECT_NAME}}
//
//   ; Then call functions like:
//   int result = {{PROJECT_NAME}}.ExampleFunction(actor)

#include <RE/Skyrim.h>
#include <SKSE/SKSE.h>

namespace {{PROJECT_NAME}}
{
    class Papyrus
    {
    public:
        static bool RegisterFunctions(RE::BSScript::IVirtualMachine* a_vm);

    private:
        // Example native functions - add your own here
        static int32_t ExampleFunction(RE::StaticFunctionTag*, RE::Actor* a_actor);
        static RE::BSFixedString GetPluginVersion(RE::StaticFunctionTag*);
    };
}
