// {{PROJECT_NAME}} - Papyrus Native Functions Implementation
// Generated by Spooky's AutoMod Toolkit

#include "papyrus.h"

namespace {{PROJECT_NAME}}
{
    bool Papyrus::RegisterFunctions(RE::BSScript::IVirtualMachine* a_vm)
    {
        if (!a_vm) {
            SKSE::log::error("Failed to register Papyrus functions: VM is null");
            return false;
        }

        // Register native functions
        // Format: a_vm->RegisterFunction("FunctionName", "ScriptName", FunctionPointer);

        a_vm->RegisterFunction("ExampleFunction", "{{PROJECT_NAME}}", ExampleFunction);
        a_vm->RegisterFunction("GetPluginVersion", "{{PROJECT_NAME}}", GetPluginVersion);

        SKSE::log::info("Registered Papyrus native functions for {}", "{{PROJECT_NAME}}");
        return true;
    }

    // Example: Get some value from an actor
    int32_t Papyrus::ExampleFunction(RE::StaticFunctionTag*, RE::Actor* a_actor)
    {
        if (!a_actor) {
            return -1;
        }

        // Example: Return actor's level
        return a_actor->GetLevel();
    }

    // Example: Return plugin version string
    RE::BSFixedString Papyrus::GetPluginVersion(RE::StaticFunctionTag*)
    {
        return PLUGIN_VERSION;
    }
}
