// {{PROJECT_NAME}} - Plugin Implementation
// Generated by Spooky's AutoMod Toolkit

#include "plugin.h"

namespace {{PROJECT_NAME}}
{
    void Plugin::Initialize()
    {
        SKSE::log::info("Initializing {}...", PLUGIN_NAME);

        // Register for SKSE messages
        auto messaging = SKSE::GetMessagingInterface();
        if (messaging) {
            messaging->RegisterListener(OnMessage);
        }

        SKSE::log::info("{} initialization complete", PLUGIN_NAME);
    }

    void Plugin::OnMessage(SKSE::MessagingInterface::Message* a_msg)
    {
        switch (a_msg->type) {
        case SKSE::MessagingInterface::kDataLoaded:
            SKSE::log::info("Data loaded");
            break;
        case SKSE::MessagingInterface::kPostLoad:
            SKSE::log::info("Post load");
            break;
        }
    }
}
