#pragma once

// {{PROJECT_NAME}} - SKSE Plugin Header
// Generated by Spooky's AutoMod Toolkit

#include <RE/Skyrim.h>
#include <SKSE/SKSE.h>

#include <spdlog/sinks/basic_file_sink.h>

namespace {{PROJECT_NAME}}
{
    class Plugin
    {
    public:
        static void Initialize();

    private:
        static void OnMessage(SKSE::MessagingInterface::Message* a_msg);
    };
}
