namespace SpookysAutomod.Papyrus.Templates;

/// <summary>
/// Generates Papyrus script templates.
/// </summary>
public class ScriptTemplateGenerator
{
    /// <summary>
    /// Generate a script that extends a base type.
    /// </summary>
    public string Generate(string scriptName, string extendsType, ScriptTemplateOptions? options = null)
    {
        options ??= new ScriptTemplateOptions();

        var lines = new List<string>();

        // Header comment
        if (!string.IsNullOrEmpty(options.Description))
        {
            lines.Add($"; {options.Description}");
            lines.Add($"; Generated by Spooky's AutoMod Toolkit");
            lines.Add("");
        }

        // Scriptname declaration
        lines.Add($"Scriptname {scriptName} extends {extendsType}");
        lines.Add("");

        // Properties
        if (options.Properties?.Count > 0)
        {
            lines.Add("; Properties");
            foreach (var prop in options.Properties)
            {
                var autoFlag = prop.AutoReadOnly ? " Auto ReadOnly" : " Auto";
                lines.Add($"{prop.Type} Property {prop.Name}{autoFlag}");
            }
            lines.Add("");
        }

        // Events based on type
        switch (extendsType.ToLowerInvariant())
        {
            case "quest":
                lines.Add("Event OnInit()");
                lines.Add("    ; Called when the quest starts");
                lines.Add("EndEvent");
                break;

            case "activator":
            case "objectreference":
                lines.Add("Event OnActivate(ObjectReference akActionRef)");
                lines.Add("    ; Called when activated");
                lines.Add("EndEvent");
                break;

            case "actor":
                lines.Add("Event OnLoad()");
                lines.Add("    ; Called when the actor loads");
                lines.Add("EndEvent");
                lines.Add("");
                lines.Add("Event OnDeath(Actor akKiller)");
                lines.Add("    ; Called when the actor dies");
                lines.Add("EndEvent");
                break;

            case "magiceffect":
                lines.Add("Event OnEffectStart(Actor akTarget, Actor akCaster)");
                lines.Add("    ; Called when the effect starts");
                lines.Add("EndEvent");
                lines.Add("");
                lines.Add("Event OnEffectFinish(Actor akTarget, Actor akCaster)");
                lines.Add("    ; Called when the effect ends");
                lines.Add("EndEvent");
                break;

            case "activemagiceffect":
                lines.Add("Event OnEffectStart(Actor akTarget, Actor akCaster)");
                lines.Add("    ; Called when the active effect starts");
                lines.Add("EndEvent");
                break;

            case "alias":
            case "referencealias":
                lines.Add("Event OnInit()");
                lines.Add("    ; Called when the alias is filled");
                lines.Add("EndEvent");
                break;

            case "perk":
                lines.Add("; Perk entry point function");
                lines.Add("Function OnPerkEntryRun(Int aiEntryPoint, ObjectReference akTarget, Actor akActor, Int aiPerkSwitch)");
                lines.Add("    ; Called when perk entry fires");
                lines.Add("EndFunction");
                break;

            default:
                lines.Add("Event OnInit()");
                lines.Add("    ; Called on initialization");
                lines.Add("EndEvent");
                break;
        }

        lines.Add("");

        // Custom functions
        if (options.Functions?.Count > 0)
        {
            lines.Add("; Custom Functions");
            foreach (var func in options.Functions)
            {
                var returnType = string.IsNullOrEmpty(func.ReturnType) ? "" : $"{func.ReturnType} ";
                var parameters = string.Join(", ", func.Parameters.Select(p => $"{p.Type} {p.Name}"));

                lines.Add($"{returnType}Function {func.Name}({parameters})");
                lines.Add("    ; TODO: Implement");
                if (!string.IsNullOrEmpty(func.ReturnType))
                {
                    var defaultReturn = func.ReturnType.ToLowerInvariant() switch
                    {
                        "int" => "0",
                        "float" => "0.0",
                        "bool" => "False",
                        "string" => "\"\"",
                        _ => "None"
                    };
                    lines.Add($"    Return {defaultReturn}");
                }
                lines.Add("EndFunction");
                lines.Add("");
            }
        }

        return string.Join(Environment.NewLine, lines);
    }

    /// <summary>
    /// Generate a simple quest script.
    /// </summary>
    public string GenerateQuestScript(string scriptName, bool hasMaintenanceFunction = true)
    {
        var options = new ScriptTemplateOptions
        {
            Description = $"Quest script: {scriptName}"
        };

        if (hasMaintenanceFunction)
        {
            options.Functions = new List<FunctionTemplate>
            {
                new FunctionTemplate
                {
                    Name = "Maintenance",
                    ReturnType = "",
                    Parameters = new List<ParameterTemplate>()
                }
            };
        }

        return Generate(scriptName, "Quest", options);
    }

    /// <summary>
    /// Generate a magic effect script.
    /// </summary>
    public string GenerateMagicEffectScript(string scriptName)
    {
        return Generate(scriptName, "ActiveMagicEffect", new ScriptTemplateOptions
        {
            Description = $"Magic effect script: {scriptName}"
        });
    }
}

public class ScriptTemplateOptions
{
    public string? Description { get; set; }
    public List<PropertyTemplate>? Properties { get; set; }
    public List<FunctionTemplate>? Functions { get; set; }
}

public class PropertyTemplate
{
    public string Name { get; set; } = "";
    public string Type { get; set; } = "";
    public bool AutoReadOnly { get; set; }
}

public class FunctionTemplate
{
    public string Name { get; set; } = "";
    public string ReturnType { get; set; } = "";
    public List<ParameterTemplate> Parameters { get; set; } = new();
}

public class ParameterTemplate
{
    public string Name { get; set; } = "";
    public string Type { get; set; } = "";
}
